### PR TITLE
Add ability to send log files

### PR DESCRIPTION
**Pull request by Epictek**
This removes the need of a desktop with logcat to be able to view log files.
Implementation is a bit dirty but it works.

### CODE REVIEW

**Review by flyrouter — COMMENTED** [review]
Thank you, we will consider your suggestions.

**Comment by flyrouter** [comment]
Good day
Thank you very much for your suggestions.
They will be considered and applied as soon as possible.
We just always do a little research and give time to fix errors and improve functions.

**Comment by bangdc90** [comment]
Hello, could you rebase the commit?

**Comment by flyrouter** [comment]
```
<<<<<<< master
import androidx.core.content.FileProvider;
=======
import androidx.constraintlayout.widget.ConstraintSet;
>>>>>>> master
```

You need to choose the right value and everything will be solved.

**Pull request merged**
